### ISSUE TITLE
Can't star an event

### ISSUE THREAD

**Issue by popey** [canonical/canonical-indico-personal-agenda#10]
Steps to reproduce
* Go to https://events.canonical.com/event/31/contributions/247/
* Ensure logged in
* Click star

![image](https://github.com/canonical/canonical-indico-personal-agenda/assets/1841272/625bde35-c11d-4d61-95a2-705ffcf161ea)

![image](https://github.com/canonical/canonical-indico-personal-agenda/assets/1841272/dacb0e9f-2163-4b60-8693-46279e7e0344)

I was able to star another event - this one https://events.canonical.com/event/31/contributions/246/

**Comment by kewisch** [comment]
Fixed by 73fb459906b23e20b90f216b6ad216bb9404e95b. Hoping to get a new version deployed tomorrow :)
